require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CrewMerchandiseOrdersController, type: :controller do

  let(:valid_attributes) { attributes_for(:crew_merchandise_order) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CrewMerchandiseOrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    @user = create(:user_with_admin_role)
    login_user(@user)
  end

  describe "GET index" do
    it "assigns all crew_merchandise_orders as @crew_merchandise_orders" do
      crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:crew_merchandise_orders)).to eq([crew_merchandise_order])
    end
  end

  describe "GET show" do
    it "assigns the requested crew_merchandise_order as @crew_merchandise_order" do
      crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
      get :show, {:id => crew_merchandise_order.to_param}, valid_session
      expect(assigns(:crew_merchandise_order)).to eq(crew_merchandise_order)
    end
  end

  describe "GET new" do
    it "assigns a new crew_merchandise_order as @crew_merchandise_order" do
      get :new, {}, valid_session
      expect(assigns(:crew_merchandise_order)).to be_a_new(CrewMerchandiseOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested crew_merchandise_order as @crew_merchandise_order" do
      crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
      get :edit, {:id => crew_merchandise_order.to_param}, valid_session
      expect(assigns(:crew_merchandise_order)).to eq(crew_merchandise_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CrewMerchandiseOrder" do
        expect {
          post :create, crew_merchandise_order: attributes_for(:crew_merchandise_order)
        }.to change(CrewMerchandiseOrder, :count).by(1)
      end

      it "assigns a newly created crew_merchandise_order as @crew_merchandise_order" do
        post :create, crew_merchandise_order: attributes_for(:crew_merchandise_order)
        expect(assigns(:crew_merchandise_order)).to be_a(CrewMerchandiseOrder)
        expect(assigns(:crew_merchandise_order)).to be_persisted
      end

      it "redirects to the created crew_merchandise_order" do
        post :create, crew_merchandise_order: attributes_for(:crew_merchandise_order)
        expect(response).to redirect_to(CrewMerchandiseOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crew_merchandise_order as @crew_merchandise_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CrewMerchandiseOrder).to receive(:save).and_return(false)
        post :create, crew_merchandise_order: { "volunteer_id" => "invalid value" }
        expect(assigns(:crew_merchandise_order)).to be_a_new(CrewMerchandiseOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CrewMerchandiseOrder).to receive(:save).and_return(false)
        post :create, crew_merchandise_order: { "volunteer_id" => "invalid value" }
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested crew_merchandise_order" do
        crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
        # Assuming there are no other crew_merchandise_orders in the database, this
        # specifies that the CrewMerchandiseOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(CrewMerchandiseOrder).to receive(:update).with({ "volunteer_id" => "5" })
        put :update, {:id => crew_merchandise_order.to_param, crew_merchandise_order: attributes_for(:crew_merchandise_order, volunteer_id: 5) }, valid_session
      end

      it "assigns the requested crew_merchandise_order as @crew_merchandise_order" do
        crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
        put :update, {:id => crew_merchandise_order.to_param, :crew_merchandise_order => valid_attributes}, valid_session
        expect(assigns(:crew_merchandise_order)).to eq(crew_merchandise_order)
      end

      it "redirects to the crew_merchandise_order" do
        crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
        put :update, {:id => crew_merchandise_order.to_param, :crew_merchandise_order => valid_attributes}, valid_session
        expect(response).to redirect_to(crew_merchandise_order)
      end
    end

    describe "with invalid params" do
      it "assigns the crew_merchandise_order as @crew_merchandise_order" do
        crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CrewMerchandiseOrder).to receive(:save).and_return(false)
        put :update, {:id => crew_merchandise_order.to_param, :crew_merchandise_order => { "volunteer_id" => "invalid value" }}, valid_session
        expect(assigns(:crew_merchandise_order)).to eq(crew_merchandise_order)
      end

      it "re-renders the 'edit' template" do
        crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CrewMerchandiseOrder).to receive(:save).and_return(false)
        put :update, {:id => crew_merchandise_order.to_param, :crew_merchandise_order => { "volunteer_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crew_merchandise_order" do
      crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => crew_merchandise_order.to_param}, valid_session
      }.to change(CrewMerchandiseOrder, :count).by(-1)
    end

    it "redirects to the crew_merchandise_orders list" do
      crew_merchandise_order = CrewMerchandiseOrder.create! valid_attributes
      delete :destroy, {:id => crew_merchandise_order.to_param}, valid_session
      expect(response).to redirect_to(crew_merchandise_orders_url)
    end
  end

end
