require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CrewMerchandiseOrderLinesController do

  # This should return the minimal set of attributes required to create a valid
  # CrewMerchandiseOrderLine. As you add validations to CrewMerchandiseOrderLine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "crew_merchandise_order" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CrewMerchandiseOrderLinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all crew_merchandise_order_lines as @crew_merchandise_order_lines" do
      crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:crew_merchandise_order_lines).should eq([crew_merchandise_order_line])
    end
  end

  describe "GET show" do
    it "assigns the requested crew_merchandise_order_line as @crew_merchandise_order_line" do
      crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
      get :show, {:id => crew_merchandise_order_line.to_param}, valid_session
      assigns(:crew_merchandise_order_line).should eq(crew_merchandise_order_line)
    end
  end

  describe "GET new" do
    it "assigns a new crew_merchandise_order_line as @crew_merchandise_order_line" do
      get :new, {}, valid_session
      assigns(:crew_merchandise_order_line).should be_a_new(CrewMerchandiseOrderLine)
    end
  end

  describe "GET edit" do
    it "assigns the requested crew_merchandise_order_line as @crew_merchandise_order_line" do
      crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
      get :edit, {:id => crew_merchandise_order_line.to_param}, valid_session
      assigns(:crew_merchandise_order_line).should eq(crew_merchandise_order_line)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CrewMerchandiseOrderLine" do
        expect {
          post :create, {:crew_merchandise_order_line => valid_attributes}, valid_session
        }.to change(CrewMerchandiseOrderLine, :count).by(1)
      end

      it "assigns a newly created crew_merchandise_order_line as @crew_merchandise_order_line" do
        post :create, {:crew_merchandise_order_line => valid_attributes}, valid_session
        assigns(:crew_merchandise_order_line).should be_a(CrewMerchandiseOrderLine)
        assigns(:crew_merchandise_order_line).should be_persisted
      end

      it "redirects to the created crew_merchandise_order_line" do
        post :create, {:crew_merchandise_order_line => valid_attributes}, valid_session
        response.should redirect_to(CrewMerchandiseOrderLine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crew_merchandise_order_line as @crew_merchandise_order_line" do
        # Trigger the behavior that occurs when invalid params are submitted
        CrewMerchandiseOrderLine.any_instance.stub(:save).and_return(false)
        post :create, {:crew_merchandise_order_line => { "crew_merchandise_order" => "invalid value" }}, valid_session
        assigns(:crew_merchandise_order_line).should be_a_new(CrewMerchandiseOrderLine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CrewMerchandiseOrderLine.any_instance.stub(:save).and_return(false)
        post :create, {:crew_merchandise_order_line => { "crew_merchandise_order" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested crew_merchandise_order_line" do
        crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
        # Assuming there are no other crew_merchandise_order_lines in the database, this
        # specifies that the CrewMerchandiseOrderLine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CrewMerchandiseOrderLine.any_instance.should_receive(:update).with({ "crew_merchandise_order" => "" })
        put :update, {:id => crew_merchandise_order_line.to_param, :crew_merchandise_order_line => { "crew_merchandise_order" => "" }}, valid_session
      end

      it "assigns the requested crew_merchandise_order_line as @crew_merchandise_order_line" do
        crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
        put :update, {:id => crew_merchandise_order_line.to_param, :crew_merchandise_order_line => valid_attributes}, valid_session
        assigns(:crew_merchandise_order_line).should eq(crew_merchandise_order_line)
      end

      it "redirects to the crew_merchandise_order_line" do
        crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
        put :update, {:id => crew_merchandise_order_line.to_param, :crew_merchandise_order_line => valid_attributes}, valid_session
        response.should redirect_to(crew_merchandise_order_line)
      end
    end

    describe "with invalid params" do
      it "assigns the crew_merchandise_order_line as @crew_merchandise_order_line" do
        crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CrewMerchandiseOrderLine.any_instance.stub(:save).and_return(false)
        put :update, {:id => crew_merchandise_order_line.to_param, :crew_merchandise_order_line => { "crew_merchandise_order" => "invalid value" }}, valid_session
        assigns(:crew_merchandise_order_line).should eq(crew_merchandise_order_line)
      end

      it "re-renders the 'edit' template" do
        crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CrewMerchandiseOrderLine.any_instance.stub(:save).and_return(false)
        put :update, {:id => crew_merchandise_order_line.to_param, :crew_merchandise_order_line => { "crew_merchandise_order" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crew_merchandise_order_line" do
      crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
      expect {
        delete :destroy, {:id => crew_merchandise_order_line.to_param}, valid_session
      }.to change(CrewMerchandiseOrderLine, :count).by(-1)
    end

    it "redirects to the crew_merchandise_order_lines list" do
      crew_merchandise_order_line = CrewMerchandiseOrderLine.create! valid_attributes
      delete :destroy, {:id => crew_merchandise_order_line.to_param}, valid_session
      response.should redirect_to(crew_merchandise_order_lines_url)
    end
  end

end
