require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MerchandiseArticleVariantsController do

  # This should return the minimal set of attributes required to create a valid
  # MerchandiseArticleVariant. As you add validations to MerchandiseArticleVariant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MerchandiseArticleVariantsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all merchandise_article_variants as @merchandise_article_variants" do
      merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
      get :index, {}, valid_session
      assigns(:merchandise_article_variants).should eq([merchandise_article_variant])
    end
  end

  describe "GET show" do
    it "assigns the requested merchandise_article_variant as @merchandise_article_variant" do
      merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
      get :show, {:id => merchandise_article_variant.to_param}, valid_session
      assigns(:merchandise_article_variant).should eq(merchandise_article_variant)
    end
  end

  describe "GET new" do
    it "assigns a new merchandise_article_variant as @merchandise_article_variant" do
      get :new, {}, valid_session
      assigns(:merchandise_article_variant).should be_a_new(MerchandiseArticleVariant)
    end
  end

  describe "GET edit" do
    it "assigns the requested merchandise_article_variant as @merchandise_article_variant" do
      merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
      get :edit, {:id => merchandise_article_variant.to_param}, valid_session
      assigns(:merchandise_article_variant).should eq(merchandise_article_variant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MerchandiseArticleVariant" do
        expect {
          post :create, {:merchandise_article_variant => valid_attributes}, valid_session
        }.to change(MerchandiseArticleVariant, :count).by(1)
      end

      it "assigns a newly created merchandise_article_variant as @merchandise_article_variant" do
        post :create, {:merchandise_article_variant => valid_attributes}, valid_session
        assigns(:merchandise_article_variant).should be_a(MerchandiseArticleVariant)
        assigns(:merchandise_article_variant).should be_persisted
      end

      it "redirects to the created merchandise_article_variant" do
        post :create, {:merchandise_article_variant => valid_attributes}, valid_session
        response.should redirect_to(MerchandiseArticleVariant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved merchandise_article_variant as @merchandise_article_variant" do
        # Trigger the behavior that occurs when invalid params are submitted
        MerchandiseArticleVariant.any_instance.stub(:save).and_return(false)
        post :create, {:merchandise_article_variant => { "name" => "invalid value" }}, valid_session
        assigns(:merchandise_article_variant).should be_a_new(MerchandiseArticleVariant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MerchandiseArticleVariant.any_instance.stub(:save).and_return(false)
        post :create, {:merchandise_article_variant => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested merchandise_article_variant" do
        merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
        # Assuming there are no other merchandise_article_variants in the database, this
        # specifies that the MerchandiseArticleVariant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MerchandiseArticleVariant.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => merchandise_article_variant.to_param, :merchandise_article_variant => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested merchandise_article_variant as @merchandise_article_variant" do
        merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
        put :update, {:id => merchandise_article_variant.to_param, :merchandise_article_variant => valid_attributes}, valid_session
        assigns(:merchandise_article_variant).should eq(merchandise_article_variant)
      end

      it "redirects to the merchandise_article_variant" do
        merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
        put :update, {:id => merchandise_article_variant.to_param, :merchandise_article_variant => valid_attributes}, valid_session
        response.should redirect_to(merchandise_article_variant)
      end
    end

    describe "with invalid params" do
      it "assigns the merchandise_article_variant as @merchandise_article_variant" do
        merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MerchandiseArticleVariant.any_instance.stub(:save).and_return(false)
        put :update, {:id => merchandise_article_variant.to_param, :merchandise_article_variant => { "name" => "invalid value" }}, valid_session
        assigns(:merchandise_article_variant).should eq(merchandise_article_variant)
      end

      it "re-renders the 'edit' template" do
        merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MerchandiseArticleVariant.any_instance.stub(:save).and_return(false)
        put :update, {:id => merchandise_article_variant.to_param, :merchandise_article_variant => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested merchandise_article_variant" do
      merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
      expect {
        delete :destroy, {:id => merchandise_article_variant.to_param}, valid_session
      }.to change(MerchandiseArticleVariant, :count).by(-1)
    end

    it "redirects to the merchandise_article_variants list" do
      merchandise_article_variant = MerchandiseArticleVariant.create! valid_attributes
      delete :destroy, {:id => merchandise_article_variant.to_param}, valid_session
      response.should redirect_to(merchandise_article_variants_url)
    end
  end

end
