name: Build and Push Docker Image

on:
  push:
    branches:
      - cicd-container-gha

env:
  container_image: europe-north1-docker.pkg.dev/crewpicker/crewpicker

jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.output-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - id: gcloud-auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT }}/locations/global/workloadIdentityPools/crewpicker-gha/providers/crewpicker-gha-provider
          service_account: gha-deployer@crewpicker.iam.gserviceaccount.com
          token_format: access_token
          access_token_lifetime: 300s
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcloud-auth.outputs.access_token }}
      - run: |
          echo "${{ secrets.NPMRC }}" > .npmrc
          cp config/database.yml.example config/database.yml
          cp config/config.yml.example config/config.yml

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.container_image }}:${{ github.sha }}
            ${{ env.container_image }}:latest
      - id: output-tag
        run: echo ::set-output tag=${{ env.container_image }}:${{ github.sha }}
  deploy:
    needs: build-and-push
    uses: crewpicker/crewpicker-infra/.github/workflows/crewpicker-pro.yaml@main
    with:
      container_image: ${{ needs.build-and-push.outputs.tag }}
